In [1]:
#in built dataset from sklearn is used
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
# fillna(): replaces na with mean mode or median from single column at a time.
# SimpleImputer will replace na from multiple columns at a time
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
# We have seen OHE: for x variables, Lable Encoding: for y variable
# OrdinalEncoder: works same as Lable Encoder but on x variables
#from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/cars_new.csv')
df

EDA

In [ ]:
df.info()
# ? is missing value because of it datatype has become object

In [ ]:
df.isna().sum() # not identified ? as missing value

In [ ]:
df['normalized-losses'].value_counts()

In [ ]:
df[df['horsepower']=='?']

In [7]:
df.replace('?',np.nan,inplace=True)

In [ ]:
df.isna().sum()

In [ ]:
df

In [10]:
df.dtypes # still normalized-losses is object, We have replaced ? with Nan with replace()
# to change data type we have to use astype()

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [11]:
df['normalized-losses']

0      NaN
1      NaN
2      NaN
3      164
4      164
      ... 
200     95
201     95
202     95
203     95
204     95
Name: normalized-losses, Length: 205, dtype: object

In [12]:
si = SimpleImputer(strategy='median')

In [ ]:
df

In [13]:
df.iloc[:,[1,11]]

normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [ ]:
# OR
df.loc[:,['normalized-losses','horsepower']]

In [14]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])
# fit will calculate median of col 1 and 11, transform: replace missing value by median

In [15]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
df

In [17]:
df.select_dtypes(int) # will display only colums of int data type, try float

symboling  engine-size  city-mpg  highway-mpg  price
0            3          130        21           27  13495
1            3          130        21           27  16500
2            1          152        19           26  16500
3            2          109        24           30  13950
4            2          136        18           22  17450
..         ...          ...       ...          ...    ...
200         -1          141        23           28  16845
201         -1          141        19           25  19045
202         -1          173        18           23  21485
203         -1          145        26           27  22470
204         -1          141        19           25  22625

[205 rows x 5 columns]

In [ ]:
df.select_dtypes(float)

In [ ]:
df.select_dtypes(object)

In [20]:
df.select_dtypes([int,float]) # all numerical columns

symboling  normalized-losses  width  height  engine-size  horsepower  \
0            3              115.0   64.1    48.8          130       111.0   
1            3              115.0   64.1    48.8          130       111.0   
2            1              115.0   65.5    52.4          152       154.0   
3            2              164.0   66.2    54.3          109       102.0   
4            2              164.0   66.4    54.3          136       115.0   
..         ...                ...    ...     ...          ...         ...   
200         -1               95.0   68.9    55.5          141       114.0   
201         -1               95.0   68.8    55.5          141       160.0   
202         -1               95.0   68.9    55.5          173       134.0   
203         -1               95.0   68.9    55.5          145       106.0   
204         -1               95.0   68.9    55.5          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 9 columns]

In [ ]:
# Encoding: selecting only categorical columns
cat_cols = df.select_dtypes(object).columns # store col names in cat_cols variable
cat_cols

In [ ]:
df[cat_cols] # extract values of all col names from cat_cols

In [23]:
oe = OrdinalEncoder() # convert categorical values to numerical
df[cat_cols] = oe.fit_transform(df[cat_cols])

In [ ]:
df

In [ ]:
df.dtypes

# **Model Building**

In [26]:
x = df.iloc[:,:-1]
y = df['price']

In [27]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [28]:
# Linear Regression Model
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)
ypred

array([ 6114.11943789,  6899.1299745 ,  5179.12129606,  6534.49022809,
        9125.91144455, 26384.12259969,  7406.15558344,   895.58275157,
        5172.9291232 , 13513.24663171, 15407.85345859, 14421.55136235,
       16418.89788598, 11145.35574554, 16463.66533212, 13896.61774947,
        7335.98228673,  8845.0632645 , 10862.74899523,  7555.18709439,
       11006.99145217,  6830.04912601, 13638.73999814,  6363.9621527 ,
       13732.90563984,  8845.0632645 , 15040.20874209,  6544.19455256,
        4706.60204753,  9314.78618354,  8128.3940468 , 14321.0634702 ,
       25655.82279003, 11987.68138692, 19723.90650907,  6557.53154026,
        8154.91470876, 30658.97297566,  9834.8439003 , 16923.44920496,
        6520.66900847, 20194.14945986,  7692.55861481,  8459.52258636,
        8670.04245903,  7166.21791784, 40486.41308962,  7569.40057796,
       17170.51789287, 18954.92930717, 26190.76513016, 16914.80136248,
       21856.35461232,  6225.96759922, 13090.60124574,  7294.0335782 ,
      

In [29]:
lr.intercept_ # y intercept i.e. c value

-64935.113579782344

In [30]:
lr.coef_ # slope or coefficient or weight

array([ 5.71727164e+01,  4.76320989e-01, -2.01309566e+02, -6.22705136e+02,
       -1.63712110e+02,  1.88863899e+03,  1.63884484e+04,  7.90632094e+02,
        3.61221503e+02,  2.81207534e+02,  9.82290864e+01, -1.06474945e+01,
        3.08435166e+02, -4.17126915e+02])

In [31]:
lr.score(xtrain,ytrain),lr.score(xtest,ytest) # Train accuracy, Test accuracy
# overfitted model as high train accuracy and low test accuracy

(0.8504229026078215, 0.796485478542952)

# **Lasso (L1) Regression**

In [32]:
# after lasso, train accuracy will decrease but test accuracy will increase
l1 = Lasso() # alpha = 0.1 by default
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain),l1.score(xtest,ytest)
# we got same accuracy and overfitted model

(0.8504215478243032, 0.7966615211575686)

In [ ]:
l1.coef_
# same as previous results: no coefficient is 0 so go for hyperparameter tuning of alpha

# **Hyperparameter Tuning**

In [ ]:
for i in range(100,200): # try 50 to 100, 100 to 200
  l1 = Lasso(alpha = i)
  l1.fit(xtrain,ytrain)
  print(f"Alpha: {i} Train: {l1.score(xtrain,ytrain)} Test: {l1.score(xtest,ytest)}")

In [36]:
# as alpha increases train accuracy decreases and test accuracy increases
# so try big alpha value
# in above code try changing range from 50 to 100, 150 to 200
l1 = Lasso(alpha = 175) # select any value where train and test accuracy is same
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain),l1.score(xtest,ytest)


(0.8107234361496893, 0.8139459609474125)

In [37]:
l1.coef_ # check columns whose slope is 0. They are not important in model building
# normalized-losses, fuel-type are not important

array([  26.15091464,   -0.        , -173.02547787,   -0.        ,
       -363.80743898, 1247.84193718, 3867.709301  ,  391.04314711,
        451.57194036,  297.35122938,  113.32977728,   11.00742675,
         70.90090498, -160.35202828])

In [38]:
xtrain.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'],
      dtype='object')

# **Ridge (L2) Regression**

In [39]:
l2 = Ridge()
l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain),l1.score(xtest,ytest)

(0.8435840853399227, 0.8139459609474125)

In [ ]:
for i in range(1,100):
  l2 = Ridge(alpha = i)
  l2.fit(xtrain,ytrain)
  print(f"Alpha: {i} Train: {l2.score(xtrain,ytrain)} Test: {l2.score(xtest,ytest)}")
  # alpha = 6 to 10 same train and test accuracies

In [43]:
l2 = Ridge(alpha = 7)
l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain),l2.score(xtest,ytest)

(0.8162882573020809, 0.8150880725612082)

In [42]:
l2.coef_

array([ 2.31139279e+02, -3.29204695e+00, -1.90126861e+02, -1.01249352e+03,
       -6.04047656e+02,  1.71736131e+03,  3.40160377e+03,  3.91530395e+02,
        5.57861287e+02,  5.13867686e+02,  1.02968876e+02,  2.01227011e+01,
        2.13425523e+02, -2.79915768e+02])

# **Elastic Net**

In [45]:
en = ElasticNet(alpha = 1) # default alpha=0.1
en.fit(xtrain,ytrain)
en.score(xtrain,ytrain),en.score(xtest,ytest)

(0.7866253599240464, 0.8098264817256129)

In [ ]:
# We can go for Ridge Regression or Lasso